export enum EMoveType {
    MOVETYPE_NONE = 0,
    MOVETYPE_ISOMETRIC = 1,
    MOVETYPE_WALK = 2,
    MOVETYPE_STEP = 3,
    MOVETYPE_FLY = 4,
    MOVETYPE_FLYGRAVITY = 5,
    MOVETYPE_VPHYSICS = 6,
    MOVETYPE_PUSH = 7,
    MOVETYPE_NOCLIP = 8,
    MOVETYPE_LADDER = 9,
    MOVETYPE_OBSERVER = 10,
    MOVETYPE_CUSTOM = 11,
}
