export enum ERoundState {
    GR_STATE_INIT = 0,
    GR_STATE_PREGAME = 1,
    GR_STATE_STARTGAME = 2,
    GR_STATE_PREROUND = 3,
    GR_STATE_RND_RUNNING = 4,
    GR_STATE_TEAM_WIN = 5,
    GR_STATE_RESTART = 6,
    GR_STATE_STALEMATE = 7,
    GR_STATE_GAME_OVER = 8,
    GR_NUM_ROUND_STATES = 11,
}
