export enum ESpectatorMode {
    OBS_MODE_NONE = 0,
    OBS_MODE_DEATHCAM = 1,
    OBS_MODE_FREEZECAM = 2,
    OBS_MODE_FIXED = 3,
    OBS_MODE_IN_EYE = 4,
    OBS_MODE_CHASE = 5,
    OBS_MODE_POI = 6,
    OBS_MODE_ROAMING = 7,
    NUM_OBSERVER_MODES = 8,
}
